<a href="https://colab.research.google.com/github/RMLAI/zero-to-mastery-ml/blob/master/Intro_to_Scikit_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
ls

Advertising.csv                      Hitters.csv
Auto.csv                             Hitters_X_test.csv
Boston.csv                           Hitters_X_train.csv
Caravan.csv                          Hitters_y_test.csv
car-photo.png                        Hitters_y_train.csv
car-sales.csv                        Khan_xtest.csv
car-sales-extended.csv               Khan_xtrain.csv
car-sales-extended-missing-data.csv  Khan_ytest.csv
car-sales-missing-data.csv           Khan_ytrain.csv
Carseats.csv                         NCI60_X.csv
covid_19_india.csv                   NCI60_y.csv
Credit.csv                           panda.png
Default.xlsx                         random_forest_model_1.pkl
dog-photo.png                        Smarket.csv
Heart.csv                            USArrests.csv
heart-disease.csv                    Wage.csv


In [5]:
cd drive/My Drive/Data

[Errno 2] No such file or directory: 'drive/My Drive/Data'
/content/drive/My Drive/Data


This notebook Demos the power of scikit learn


*   Getting data ready

*   Choose right algorithm for problem

*   Fit model/algorithm for data , make predictions
*   Evaluate and improve model


*   Load trained model


*   Put it all together



In [0]:
#import necesseary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
#Getting the data ready
heart_disease=pd.read_csv('heart-disease.csv')
heart_disease.head(10)

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1
5   57    1   0       140   192    0  ...      0      0.4      1   0     1       1
6   56    0   1       140   294    0  ...      0      1.3      1   0     2       1
7   44    1   1       120   263    0  ...      0      0.0      2   0     3       1
8   52    1   2       172   199    1  ...      0      0.5      2   0     3       1
9   57    1   2       150   168    0  ...      0      1.6      2   0     2       1

[10 rows x 14 columns]

In [0]:
# Creating the predictor variable and target variable matrix
X=heart_disease.drop('target',axis=1)
y=heart_disease['target']

In [0]:
#checkinng the shape of the predictor and target variables
X.shape,y.shape

((303, 13), (303,))

#2 Choosing the right model and hyperparameters

In [0]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

#checking the default parameters
clf.get_params

<bound method BaseEstimator.get_params of RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)>

In [0]:
#3 Assigining observations to testing and training datasets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

NameError: ignored

In [0]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [0]:
#fitting the data to the model
clf.fit(X_train,y_train);

In [0]:
#make predictions
y_preds = clf.predict(X_test)

In [0]:
#Actual vs predictions
Check=pd.DataFrame({'Actual':y_test,'Prediction':y_preds})
Check.head(25)

ERROR! Session/line number was not unique in 

Actual  Prediction
225       0           0
152       1           1
228       0           1
201       0           0
52        1           0
245       0           1
175       0           0
168       0           0
223       0           0
217       0           0
111       1           1
135       1           1
218       0           0
12        1           1
15        1           1
66        1           1
97        1           0
90        1           1
198       0           0
103       1           1
22        1           1
212       0           0
226       0           0
264       0           0
133       1           1

database. History logging moved to new session 60


In [0]:
clf.score(X_train,y_train)

1.0

In [0]:
clf.score(X_test,y_test)

0.8688524590163934

In [0]:
# import and test the accuracy metrics ofthe model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.88      0.81      0.85        27
           1       0.86      0.91      0.89        34

    accuracy                           0.87        61
   macro avg       0.87      0.86      0.87        61
weighted avg       0.87      0.87      0.87        61



In [0]:
print(confusion_matrix(y_test,y_preds))

[[22  5]
 [ 3 31]]


In [0]:
print('accuracy:%.2f' %accuracy_score(y_test,y_preds))

accuracy:0.87
ERROR! Session/line number was not unique in database. History logging moved to new session 62


In [0]:
# Improve the model
# Trying different n_estimators
np.random.seed(42)
for i in range(10,100,10):
  print(f'Trying model with {i} estimators')
  clf = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
  print(f'Model accuracy on test set:{clf.score(X_test,y_test)*100:.2f}%')
  print(' ')

Trying model with 10 estimators
Model accuracy on test set:81.97%
 
Trying model with 20 estimators
Model accuracy on test set:80.33%
 
Trying model with 30 estimators
Model accuracy on test set:81.97%
 
Trying model with 40 estimators
Model accuracy on test set:85.25%
 
Trying model with 50 estimators
Model accuracy on test set:90.16%
 
Trying model with 60 estimators
Model accuracy on test set:83.61%
 
Trying model with 70 estimators
Model accuracy on test set:83.61%
 
Trying model with 80 estimators
Model accuracy on test set:88.52%
 
Trying model with 90 estimators
Model accuracy on test set:86.89%
 


In [0]:
#saving a model
import pickle
pickle.dump(clf,open('random_forest_model_1.pkl','wb'))

In [0]:
#loading the model
loaded_model = pickle.load(open('random_forest_model_1.pkl','rb'))
print(f'loaded model acccuracy:{loaded_model.score(X_test,y_test)*100 :.2f}%');

loaded model acccuracy:86.89%


In [0]:
#loading car sales dataset
car_sales = pd.read_csv('car-sales-extended.csv')
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [0]:
car_sales.shape

(1000, 5)

In [0]:
from sklearn.model_selection import train_test_split
#splitting data into training and test sets
X = car_sales.drop('Price',axis=1)
y = car_sales['Price']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [0]:
#Building a ML Model
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)

ValueError: ignored

In [0]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',one_hot,categorical_features)],remainder='passthrough')

In [0]:
transformed_X = transformer.fit_transform(X)
transformed_X[:5]

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 8.47140e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 1.54365e+05],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 1.81577e+05]])

In [0]:
transformed_X.shape

(1000, 13)

In [0]:
#another way to transform categorical data
dummies = pd.get_dummies(car_sales[['Make','Colour','Doors']])
dummies

Doors  Make_BMW  Make_Honda  ...  Colour_Green  Colour_Red  Colour_White
0        4         0           1  ...             0           0             1
1        5         1           0  ...             0           0             0
2        4         0           1  ...             0           0             1
3        4         0           0  ...             0           0             1
4        3         0           0  ...             0           0             0
..     ...       ...         ...  ...           ...         ...           ...
995      4         0           0  ...             0           0             0
996      3         0           0  ...             0           0             1
997      4         0           0  ...             0           0             0
998      4         0           1  ...             0           0             1
999      4         0           0  ...             0           0             0

[1000 rows x 10 columns]

In [0]:
#fitting the model again with transformed variables
X_train,X_test,y_train,y_test = train_test_split(transformed_X,y,test_size=0.2,random_state=0)

In [0]:
model.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [0]:
model.score(X_test,y_test)

0.34532974807163475

Handling missing values with Pandas

In [0]:
car_sales_missing=pd.read_csv('car-sales-extended-missing-data.csv')
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [0]:
#which columns are having missing values
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [0]:
#Create X & y
X = car_sales_missing.drop('Price',axis=1)
y=car_sales_missing['Price']
X.shape,y.shape,X.head(),y.head()

((1000, 4), (1000,),      Make Colour  Odometer (KM)  Doors
 0   Honda  White        35431.0    4.0
 1     BMW   Blue       192714.0    5.0
 2   Honda  White        84714.0    4.0
 3  Toyota  White       154365.0    4.0
 4  Nissan   Blue       181577.0    3.0, 0    15323.0
 1    19943.0
 2    28343.0
 3    13434.0
 4    14043.0
 Name: Price, dtype: float64)

In [0]:
#turning the categorical variables to numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',one_hot,categorical_features)],remainder = 'passthrough')

transformed_X = transformer.fit_transform(X)
transformed_X


ValueError: ignored

In [0]:
#The error at the top is because the make column contains missing values

In [0]:
car_sales_missing['Doors'].value_counts()

4.0    811
5.0     75
3.0     64
Name: Doors, dtype: int64

In [0]:
#filling the missing columns
car_sales_missing['Make'].fillna('missing',inplace=True)
car_sales_missing['Colour'].fillna('missing',inplace=True)
car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean,inplace=True)
car_sales_missing['Doors'].fillna(4,inplace=True)

In [0]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [0]:
#dropping the price rows with missing values as we should not filll the target columns with imputed values etc.
car_sales_missing.dropna(inplace=True)

In [0]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [0]:
#making the predictor and target variables
X=car_sales_missing.drop('Price',axis=1)
y=car_sales_missing['Price']

In [0]:
#turning the categorical variables to numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',one_hot,categorical_features)],remainder = 'passthrough')

transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

array([[0.0, 1.0, 0.0, ..., 0.0, 35431.0, 15323.0],
       [1.0, 0.0, 0.0, ..., 1.0, 192714.0, 19943.0],
       [0.0, 1.0, 0.0, ..., 0.0, 84714.0, 28343.0],
       ...,
       [0.0, 0.0, 1.0, ..., 0.0, 66604.0, 31570.0],
       [0.0, 1.0, 0.0, ..., 0.0, 215883.0, 4001.0],
       [0.0, 0.0, 0.0, ..., 0.0, 248360.0, 12732.0]], dtype=object)

In [0]:
#try to test the model now
X_train,X_test,y_train,y_test = train_test_split(transformed_X,y)

In [0]:
#fitting the random forest regressor
model.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [0]:
#scoring the model on training data
model.score(X_train,y_train)

0.8937101720037295

In [0]:
#scoring the model on testing data
model.score(X_test,y_test)

0.3344507234811712

Handling missing values with Scikit Learn

In [0]:
#loading the dataset
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

car_sales_missing=pd.read_csv('car-sales-extended-missing-data.csv')
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [0]:
car_sales_missing.dropna(subset=['Price'],inplace=True)

In [0]:
car_sales_missing.shape

(950, 5)

In [0]:
#creating the predictor and resonse variable
X=car_sales_missing.drop('Price',axis=1)
y=car_sales_missing['Price']
X.shape,y.shape

((950, 4), (950,))

In [0]:
#filling the missing values
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#fill the categorical values with missing and numerical values with mean
cat_imputer = SimpleImputer(strategy='constant',fill_value='missing')
door_imputer=SimpleImputer(strategy='constant',fill_value=4)
num_imputer=SimpleImputer(strategy='mean')

#Define columns
cat_features=['Make','Colour']
door_features=['Doors']
num_features=['Odometer (KM)']

#Create the imputer

imputer = ColumnTransformer([
                             ('cat_imputer',cat_imputer,cat_features),
                             ('door_imputer',door_imputer,door_features),
                             ('num_imputer',num_imputer,num_features)
])

filled_X=imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [0]:
#converting the array into dataframe
car_sales_filled = pd.DataFrame(filled_X,columns=['Make','Colour','Doors','Odometer (KM)'])
car_sales_filled.head()


Make Colour Doors Odometer (KM)
0   Honda  White     4         35431
1     BMW   Blue     5        192714
2   Honda  White     4         84714
3  Toyota  White     4        154365
4  Nissan   Blue     3        181577

In [0]:
#checking for missing values
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [0]:
#turning the categorical variables to numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',one_hot,categorical_features)],remainder = 'passthrough')

transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [0]:
#splitting data and making,scorinng the model
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(transformed_X,y,test_size=0.2,random_state=0)

model=RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.15874656822356636

# *3. Choosing the right model and Modeling *

In [0]:
#1.Picking the right model for regression problem
#2.Picking the right model for classification problem

In [0]:
#import the boston housing dataset
from sklearn.datasets import load_boston
boston = load_boston()
boston

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate p

In [0]:
boston_df = pd.DataFrame(boston['data'],columns=boston['feature_names'])
boston_df['target']=pd.Series(boston['target'])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  target
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98    24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14    21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03    34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94    33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33    36.2

[5 rows x 14 columns]

In [0]:
#Try ridge regression model
from sklearn.linear_model import Ridge

X=boston_df.drop('target',axis=1)
y=boston_df['target']

#splitting the data
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

#instantiate ridge model
model=Ridge()
model.fit(X_train,y_train)

#scoring the model
model.score(X_train,y_train),model.score(X_test,y_test)

NameError: ignored

#Choosing the estimator for classification problem
https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [0]:
#loading the heart disease dataset
heart_disease = pd.read_csv('heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [0]:
heart_disease.shape

(303, 14)

In [0]:
#importing the model, splitting data into training and test sets
from sklearn.svm import LinearSVC

#Make Predictor and response variables
X=heart_disease.drop('target',axis=1)
y=heart_disease['target']

#split data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [0]:
#Instantiate the model and evaluate score
model = LinearSVC()
model.fit(X_train,y_train)
model.score(X_train,y_train),model.score(X_test,y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


(0.7231404958677686, 0.6721311475409836)

In [0]:
#Try randomforest regressor for boston housing data
#Try ridge regression model
from sklearn.ensemble import RandomForestRegressor

X=boston_df.drop('target',axis=1)
y=boston_df['target']

#splitting the data
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

#instantiate ridge model
model=RandomForestRegressor()
model.fit(X_train,y_train)

#scoring the model
model.score(X_train,y_train),model.score(X_test,y_test)

(0.983002849709739, 0.7366913061531987)

In [0]:
#Try RF classifier for heart disease dataset
#loading the heart disease dataset
heart_disease = pd.read_csv('heart-disease.csv')
#importing the model, splitting data into training and test sets
from sklearn.ensemble import RandomForestClassifier

#Make Predictor and response variables
X=heart_disease.drop('target',axis=1)
y=heart_disease['target']

#split data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [0]:
#Instantiate the model and evaluate score
model = RandomForestClassifier()
model.fit(X_train,y_train)
model.score(X_train,y_train),model.score(X_test,y_test)

(1.0, 0.8688524590163934)

# **Making Prediction with our data**

1.Using predict()
2.Using predict_proba()





In [0]:
model.predict(X_train)

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0])

In [0]:
y_train

74     1
153    1
64     1
296    0
287    0
      ..
251    0
192    0
117    1
47     1
172    0
Name: target, Length: 242, dtype: int64

In [0]:
#compare the results
y_preds=model.predict(X_test)
np.mean(y_preds==y_test)

0.8688524590163934

In [0]:
model.score(X_test,y_test)

0.8688524590163934

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_preds,y_test)

0.8688524590163934

In [0]:
#This predicts the probabilities of the outcomes of the classification
model.predict_proba(X_test[:5])

array([[0.78, 0.22],
       [0.45, 0.55],
       [0.35, 0.65],
       [1.  , 0.  ],
       [0.89, 0.11]])

**Predicting the outcomes for a regression Model**

In [0]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)

In [0]:
#Loadinng the data into the X,y
X = boston_df.drop('target',axis=1)
X.shape

(506, 13)

In [0]:
y = boston_df['target']
y.shape

(506,)

In [0]:
# Splitting the data into train test split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2)

In [0]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((404, 13), (102, 13), (404,), (102,))

In [0]:
#Fitting the model on the training data
model = RandomForestRegressor()
model.fit(X_train,y_train);

In [0]:
# Predicting and stroing outcomes in new array
y_preds = model.predict(X_test)

In [0]:
#Checking the 1st 5 predictions
y_preds[:5]

array([21.399, 28.697, 25.167, 18.331, 19.781])

In [0]:
#Checking the 1st 5 actual values
np.array(y_test[:5])

array([23. , 32. , 24.1, 17.1, 20.8])

**EVALUATING A MACHINE LEARNING MODEL** 
3 Ways to evaluate a ML model

1.Score method
2.Scoring parameter
3.Problem specific metrics functions


In [0]:
#importing the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [0]:
#loading the dataset
heart_disease = pd.read_csv('heart-disease.csv')

In [0]:
#Creating the train test splits
X = heart_disease.drop('target',axis=1)
y = heart_disease['target']
X.shape,y.shape

((303, 13), (303,))

In [0]:
#Splittng the data into train and test sets
np.random.seed(42)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
model = RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
#check the score of the model
model.score(X_train,y_train),model.score(X_test,y_test)

(1.0, 0.8524590163934426)

**Evaluating the cross val scores**

In [0]:
from sklearn.model_selection import cross_val_score

In [0]:
cross_val_score(model,X,y,cv=10)

array([0.90322581, 0.80645161, 0.90322581, 0.9       , 0.83333333,
       0.86666667, 0.8       , 0.83333333, 0.73333333, 0.8       ])

**Evaluating the model with other scoring parameters**

Classication model Evaluation metrics
1.Accuracy
2.Area Under the Curve
3.Confusion matrix
4.Classification report

**1.Accuracy**

In [0]:
#Importing the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [8]:
#loading the dataset
heart_disease = pd.read_csv('heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [0]:
X = heart_disease.drop('target',axis=1)
y=heart_disease['target']

In [0]:
#splittin the data into training and testing sets
np.random.seed(42)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)
model = RandomForestClassifier()
model.fit(X_train,y_train)
cv_score = cross_val_score(model,X,y,cv=5,scoring=None)


In [0]:
cv_score,np.mean(cv_score)

(array([0.81967213, 0.86885246, 0.81967213, 0.78333333, 0.76666667]),
 0.811639344262295)

In [0]:
print(f'Heart Disease Classifier Cross Validated Accuracy :{np.mean(cv_score)*100:.2f}%')

Heart Disease Classifier Cross Validated Accuracy :81.16%


2.AREA UNDER THE CURVE/ROC Curve
ROC curves are a comparison of the model's true positive rate(tpr) versus the false positive rate(fpr) 

*   True positive = model predicts 1 when truth is 1
*   False positive = model predicts 1 when truth is 0
*   True negative = model predicts 0 when truth is 0
*   False negative = model predicts 0 when truth is 1

